"""
Django settings for imageform project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = BASE_DIR / 'template'
STATIC_DIR = BASE_DIR / 'static'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b(vh2j7-si^o*7-n3b2p*ecbjf_z$#=a1sp%8stk&bh-m+22_&'



RECAPTCHA_PUBLIC_KEY = '6Lfh8nwjAAAAAPP1CAfWn82qpnmTxa1xYpJ4b0RW'
RECAPTCHA_PRIVATE_KEY = '6Lfh8nwjAAAAADxHeWpQKg26OzKlnJTqqesbv8ue'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'application1',
    'rest_framework_simplejwt',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'imageform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',


            ],
        },
    },
]

WSGI_APPLICATION = 'imageform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
                       STATIC_DIR
                 ]
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/image')
MEDIA_URL = '/media/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

JWT_AUTH = {
 'JWT_ENCODE_HANDLER':
 'rest_framework_jwt.utils.jwt_encode_handler',
 'JWT_DECODE_HANDLER':
 'rest_framework_jwt.utils.jwt_decode_handler',
 'JWT_PAYLOAD_HANDLER':
 'rest_framework_jwt.utils.jwt_payload_handler',
 'JWT_PAYLOAD_GET_USER_ID_HANDLER':
 'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',
 'JWT_RESPONSE_PAYLOAD_HANDLER':
 'rest_framework_jwt.utils.jwt_response_payload_handler',
 'JWT_GET_USER_SECRET_KEY': None,
 'JWT_PUBLIC_KEY': None,
 'JWT_PRIVATE_KEY': None,
 'JWT_ALGORITHM': 'HS256',
 'JWT_VERIFY': True,
 'JWT_VERIFY_EXPIRATION': True,
 'JWT_LEEWAY': 0,
 'JWT_AUDIENCE': None,
 'JWT_ISSUER': None,
 'JWT_ALLOW_REFRESH': False,
 'JWT_AUTH_HEADER_PREFIX': 'JWT',
 'JWT_AUTH_COOKIE': None,
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
