# Generated by Django 4.1.1 on 2022-12-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='document',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
